Iter5
Hobrus/hobrusmetrics pull request #5
Opened 2024-10-03 20:39 UTC by Hobrus

Доработайте агент, чтобы он мог изменять свои параметры запуска по умолчанию через переменные окружения:
ADDRESS отвечает за адрес эндпоинта HTTP-сервера.
REPORT_INTERVAL позволяет переопределять reportInterval.
POLL_INTERVAL позволяет переопределять pollInterval.
Значения интервалов времени должны задаваться в секундах.
Доработайте сервер, чтобы он мог изменять свои параметры запуска по умолчанию через переменные окружения:
ADDRESS отвечает за адрес эндпоинта HTTP-сервера.
Приоритет параметров должен быть таким:
Если указана переменная окружения, то используется она.
Если нет переменной окружения, но есть аргумент командной строки (флаг), то используется он.
Если нет ни переменной окружения, ни флага, то используется значение по умолчанию.

2024-10-07 09:33 UTC, arttet requested changes
- [x] Split the application into layers
https://medium.com/@deanrubin/the-three-layered-architecture-fe30cb0e4a6#:~:text=The%20presentation%20layer%20is%20the,Update%20or%20Delete)%20operation%20flow.
- [x] Please integrate CodeCov https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- [x] Please read and use the Conventional Commits specification https://www.conventionalcommits.org/en/v1.0.0/
- [ ] Please integrate the linter https://github.com/golangci/golangci-lint-action
- [x] Please delete deprecated constraints in CI
https://github.com/Hobrus/hobrusmetrics/blob/ec2903f6d39114e9989cfc879951aa4dbb29390e/.github/workflows/mertricstest.yml#L66

2024-10-07 11:55 UTC, Hobrus commented on internal/handlers/handlers.go
> +		<html>
embeded

2024-10-07 11:57 UTC, Hobrus commented on internal/service/metrics.go
> +	case "gauge":
Через константы

2024-10-07 14:49 UTC, Hobrus commented on internal/repositories/storage.go
> +package repositories
Done

2024-10-07 17:17 UTC, Hobrus commented on internal/handlers/handlers.go
> +func (h *Handler) updateHandler() gin.HandlerFunc {
Done

2024-10-07 17:27 UTC, Hobrus commented on internal/handlers/handlers.go
> +		<html>
Done

2024-10-07 17:30 UTC, Hobrus commented on internal/service/metrics.go
> +			return fmt.Sprintf("%d", value), nil
Не понимаю что не так, если честно и зачем, лучше напиши сначала

2024-10-07 17:35 UTC, Hobrus commented on internal/service/metrics.go
> +	case "gauge":
Не понимаю как переписать, если только не оставить два маршрута так сказать для gauge и counter, однако если добавится metricType третий тип, то вся логика поплывет

2024-10-07 17:36 UTC, Hobrus commented on internal/handlers/handlers.go
> +		<html>
Done

2024-10-07 17:41 UTC, Hobrus commented on internal/handlers/handlers.go
> +		<html>
Не понимаю как правильно эмбединги прописать

2024-10-08 19:20 UTC, arttet commented on internal/handlers/handlers.go
> +		<html>
```
import (
	"embed"
	"log"
	"net/http"
)

//go:embed internal/embedtest/testdata/*.txt
var content embed.FS

func main() {
	mux := http.NewServeMux()
	mux.Handle("/", http.FileServer(http.FS(content)))
	err := http.ListenAndServe(":8080", mux)
	if err != nil {
		log.Fatal(err)
	}
}
```

But you will have other package.

2024-10-15 00:18 UTC, Hobrus commented on internal/handlers/handlers.go
> +		<html>
Сделал по другому

2024-10-15 00:20 UTC, Hobrus commented on internal/service/metrics.go
> +			return fmt.Sprintf("%d", value), nil
Нельзя заменить fmt.Sprintf на strconv.Atoi, потому что strconv.Atoi используется для преобразования строки в целое число, а не для обратной операции.

2024-10-15 00:25 UTC, Hobrus commented on internal/service/metrics.go
> +	case "gauge":
Сделал

2024-10-16 16:38 UTC, arttet approved these changes

2024-10-16 16:38 UTC, arttet commented on .github/workflows/mertricstest.yml
> -          github.head_ref == 'iter1' ||
[CHANGE REQUEST] This test doesn't run

2024-10-16 16:38 UTC, arttet commented on cmd/server/main.go
> +	"github.com/gin-gonic/gin"
[CHANGE REQUEST] Please sort imports https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2024-10-16 16:38 UTC, arttet commented on internal/app/server/handlers/template/metrics.html
> +        <h1>Metrics</h1>
[SUGGESTION] https://github.com/golang-standards/project-layout/tree/master/web

2024-10-16 16:50 UTC, arttet commented on internal/service/metrics.go
> +			return fmt.Sprintf("%d", value), nil
P.S. `strconv.Itoa`

2024-10-16 16:51 UTC, arttet commented on internal/service/metrics.go
> +			return fmt.Sprintf("%d", value), nil
https://pkg.go.dev/strconv

2024-10-26 21:10 UTC, merged